name: greet

on:
    push:
        branches: [main]

jobs:
    greet:
        runs-on: ubuntu-latest
        steps:
            - name: say hello
              run: echo "Hello from newwww github actions.!"