name: Manual Workflow

on:

    workflow_dispatch:
        inputs:
            environment:
                description: "Choose environment"
                required: true
                default: "staging"

jobs:
    manual-jobs:
        runs-on: ubuntu-latest

        steps:
            - name: Print environment
              run: 'echo "Deploying to new ${{ github.event.inputs.environment }}"'
